name: Python application
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: check current location dir
      run: pwd

    - name: check python version
      run: python --version

    - name: check node version
      run: node --version

    - name: running python script sample.py
      run: python .github/workflows/sample.py

    # - name: Set up Python 3.10
    #   uses: actions/setup-python@v3
    #   with:
    #     python-version: "3.10"
    # - name: Install Python dependencies
    #   run: |
    #     python -m pip install --upgrade pip
